version: "3.8"

services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=cursonodejs
    ports:
      - "3306:3306"
    networks:
      - net-dev
    volumes:
      - data-mysqs-nodejs11-vol:/var/lib/mysql

networks:
  net-dev:
    driver: bridge

volumes:
  data-mysqs-nodejs11-vol:
