version: '3.8'

services:
  server:
    build: .
    container_name: server
    ports:
      - '3500:8080'
    depends_on:
      - mysql-server
      - redis
    networks:
      - net-dev
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=user
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=cursonodejs
    ports:
      - '3306:3306'
    networks:
      - net-dev
    volumes:
      - data-mysqs-nodejs11-vol:/var/lib/mysql

  sonarqube:
    image: sonarqube:8-community
    container_name: sonarqube
    ports:
      - '9000:9000'
      - '9092:9092'
    networks:
      - net-dev

  redis:
    image: redis:6.0.5-alpine
    container_name: server-redis
    command: redis-server --requirepass todovale
    ports:
      - '6380:6379'
    restart: always
    networks:
      - net-dev

  locust-master:
    build:
      context: .
      dockerfile: locust/Dockerfile
    container_name: locust-master
    ports:
      - '8089:8089'
    command: '--host https://87d5-38-25-16-207.ngrok.io --master'
    networks:
      - net-dev

  locust-slave:
    build:
      context: .
      dockerfile: locust/Dockerfile
    command: '--host https://87d5-38-25-16-207.ngrok.io --master-host=locust-master --slave'
    networks:
      - net-dev

networks:
  net-dev:
    driver: bridge

volumes:
  data-mysqs-nodejs11-vol:
